name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build NickelMenu
    runs-on: ubuntu-latest
    container: ghcr.io/pgaskin/nickeltc:1.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build KoboRoot.tgz
        run: make clean && make koboroot

      - name: Upload KoboRoot.tgz
        uses: actions/upload-artifact@v3
        with:
          name: KoboRoot-NickelMenu
          path: KoboRoot.tgz
